### ISSUE TITLE
Support for non-enum function arguments?

### ISSUE THREAD

**Issue by Boscop** [frankfralick/openai-func-enums#2]
Thanks for making this crate, it seems very useful :)

But I'm wondering why does it have the restriction that function arguments must be enums?

It would be much more useful it it also allowed function arguments of normal primitive types, like string, int, float..

E.g. if GPT should invoke an external function for certain calculations or type checking generated code.. 

Would it be possible to allow primitive types?

**Comment by frankfralick** [comment]
It doesn't require that arguments are enums. It requires that functions are described as enums. Your functions can take value types. Look in the readme at the calculator example (under clap integration) where you have functions like "Add" that takes two f64 arguments. These could be whatever value type. Let me know if I misunderstood your question.
