### ISSUE TITLE
Macros Hygiene

### ISSUE THREAD

**Issue by gusinacio** [frankfralick/openai-func-enums#3]
The current macros needs a lot of imports to be used. It would be nice if it just works by importing the macro and not needing to worry about anything else.

**Comment by frankfralick** [comment]
Sorry for the.....um.....6 month delay!  I think what you may be asking is why you are required to take dependencies to other crates besides this one just to be able to use it. 

The thing to understand is that a procedural macro crate generates code in your project at compile time. It isn't a library that you are calling into, it is adding types and functions to your source. So if that generated code depends on tokio runtime being present, you have to take a dependency to tokio too. Same with async-openai. "_Well that's super annoying_!" Well...sort of, but macros save a lot of effort, this one included. The source for the clap example is ~260 lines long, but if you use cargo expand to see the generated code, it is something like 6,250 lines. Not all of that is generated off of this crate, but most. We can't use code-generating macros and hide the underlying dependencies simultaneously.

I also thought maybe you were saying there are unused or unnecessary dependencies. I did spend time while updating this library for async-openai changes to try to ensure this library isn't bringing more than it requires. Neither rust-analyzer or clippy throw up any warnings about unused (however they have limitations when it comes to procedural macros). I just ran [udeps](https://github.com/est31/cargo-udeps) on it and that tool states that all dependencies are used. I've run that on both the examples as well with the same result.

If I've misunderstood your issue, please let me know!

**Comment by gusinacio** [comment]
Heyy, thanks for replying.

Actually, my request was about the need of importing things other than the macro. 

I think the dependencies are okay and something to expect your lib's users to have. That being said, what I was requesting is to use the fully qualified path while expanding the macro so people don't need to also import other things (`use serde_json::Value;` for example).

**Comment by gusinacio** [comment]
You can use [this](https://gist.github.com/Kestrer/8c05ebd4e0e9347eb05f265dfb7252e1) as a guide about macro hygiene.

**Comment by frankfralick** [comment]
Ok. If you look at the example code now you will see there are way fewer imports required. The ones that are left are used in the examples. Thanks again for the issue.
