### ISSUE TITLE
Documentation around environment variables

### ISSUE THREAD

**Issue by warfaj** [frankfralick/openai-func-enums#4]
Hi,

I was trying to use the crate and didn't know that you required certain environment variables to be set like `FUNC_ENUMS_EMBED_MODEL` in order to use the ToolSet macro. Without setting those variables, it gives an unintelligible unwrap error. Could you document what env variables are necessary to run this crate somewhere? 
I don't need any of the embedding functionality but those paths seem to be required to run the macro.

**Comment by frankfralick** [comment]
Super sorry about that. Working on it.

**Comment by frankfralick** [comment]
Version 0.4.0 documents environment variables.
